// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8JltrwCuI98QqVWJ7gg-qvqs2gvs6dWg',
    appId: '1:1035096802672:web:9d5f5fb6c5f21dc9c53bb5',
    messagingSenderId: '1035096802672',
    projectId: 'digitalgunluk-bfcd7',
    authDomain: 'digitalgunluk-bfcd7.firebaseapp.com',
    storageBucket: 'digitalgunluk-bfcd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkclPk-UroHXQPHlh-bSoPmztk4RijkLw',
    appId: '1:1035096802672:android:c27c31fc9672446ec53bb5',
    messagingSenderId: '1035096802672',
    projectId: 'digitalgunluk-bfcd7',
    storageBucket: 'digitalgunluk-bfcd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH8Or_YveAN1anOr-kkQbggUoko5XQ5Ro',
    appId: '1:1035096802672:ios:8e81b25b795b6df3c53bb5',
    messagingSenderId: '1035096802672',
    projectId: 'digitalgunluk-bfcd7',
    storageBucket: 'digitalgunluk-bfcd7.firebasestorage.app',
    iosBundleId: 'com.omeragac.digitalgunluk',
  );
}
